services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: db_agrotis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
